name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go install

    - name: Test code
      run: go test github.com/michimani/aws-lambda-api-go/... -shuffle=on

  create-release:
    name: Build extension
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build extension and zip it
      run: |
        make build
        cd bin && zip -r extension.zip extensions/

    - name: Create new release with asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: bin/extension.zip
